import os
import pdb

Import('env')
Import('deps')
Import('compile_design')

env = env.Clone()
cwd = Dir('#./src/example_slave/axi4lite').srcnode().abspath

src = [File('main.cc')]
src_sc = [File('sc_target.cc'), File('target_to_axi4lite.cc')]

vfiles = [File(os.path.join(cwd, 'axilite_dev.v'))]

verilated_o, verilated_obj, verilated_header = compile_design(env, vfiles, "axilite_dev", "axi4lite_dev")

verilated_dir = os.path.dirname(verilated_header)

#pdb.set_trace()

env.Append(CPPPATH=[verilated_dir])
env.Append(CPPPATH=env['VERILATOR_ROOT'] + '/include')

obj_sc = env.Object(src_sc)

env.Depends(obj_sc, verilated_header)

vdeps = []
vdeps.append(File(verilated_o))
vdeps.append(File(verilated_obj))

bin = env.Program('gem5.sc', src + src_sc + deps + vdeps)


Return('bin')
