import os
import pdb

Import('env')
Import('deps')
Import('compile_design')

env = env.Clone()
gem5_root = env['GEM5_ROOT']

src = [File('main.cc')]
src_sc = [File('sc_target.cc'), File('sc_initiator.cc'), File('top.cc')]

#axi_vpath = os.path.join(gem5_root, 'ext/axi')

vfiles = [File(os.path.join(Dir('.').abspath, 'axi_join.v'))]


verilated_o, verilated_obj, verilated_header = compile_design(env, vfiles, "axi_join", "axi_join")

verilated_dir = os.path.dirname(verilated_header)


env.Append(CPPPATH=[verilated_dir])
env.Append(CPPPATH=env['VERILATOR_ROOT'] + '/include')

obj_sc = env.Object(src_sc)

env.Depends(obj_sc, verilated_header)

vdeps = []
vdeps.append(File(verilated_o))
vdeps.append(File(verilated_obj))


bin = env.Program('gem5.sc', src + src_sc + deps + vdeps)


Return('bin')
