# -*- mode:python -*-

# Copyright (c) 2011 Mark D. Hill and David A. Wood
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#


Import('*')

Source('addrdec.cc')
Source('dram.cc', append={'CXXFLAGS': '-Wno-error=format -Wno-error=return-type -Wno-error=unused-variable'})
Source('dram_sched.cc')
Source('gpu-cache.cc', append={'CXXFLAGS': '-Wno-error=format -Wno-error=unused-variable -Wno-error=return-type'})
Source('gpu-cache_gem5.cc')
Source('gpu-misc.cc')
Source('gpu-sim.cc', append={'CXXFLAGS': '-Wno-error=format'})
Source('histogram.cc')
Source('icnt_wrapper.cc')
Source('l2cache.cc', append={'CXXFLAGS': '-Wno-error=format'})
#Source('l2cache_trace.cc')
Source('local_interconnect.cc', append={'CXXFLAGS': '-Wno-error=sequence-point'})
#Source('mem_fetch.cc', append={'CXXFLAGS': '-Wno-error=nonnull-compare'})
Source('mem_fetch.cc')
Source('mem_latency_stat.cc')
#Source('power_interface.cc')
Source('power_stat.cc')
Source('scoreboard.cc', append={'CXXFLAGS': '-Wno-error=ignored-qualifiers'})
Source('shader.cc', append={'CXXFLAGS': '-Wno-error=format -Wno-error=reorder -Wno-error=sequence-point -Wno-error=type-limits'})
#Source('shader_trace.cc', append={'CXXFLAGS': '-Wno-error=format'})
Source('stack.cc')
Source('stat-tool.cc', append={'CXXFLAGS': '-Wno-error=format'})
Source('traffic_breakdown.cc')
Source('visualizer.cc')
Source('hashing.cc')

#Source('fq_push_m5.cc')

