# -*- mode:python -*-

# Copyright (c) 2011 Mark D. Hill and David A. Wood
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

Import('*')

Source('cuda-sim.cc', append={'CXXFLAGS': '-Wno-error=ignored-qualifiers -Wno-error=format  -Wno-error=unused-but-set-variable -Wno-error=write-strings -Wno-error=unused-variable'})
Source('cuda_device_printf.cc', append={'CXXFLAGS': '-Wno-error=ignored-qualifiers'})
Source('cuda_device_runtime.cc', append={'CXXFLAGS': '-Wno-error=ignored-qualifiers -Wno-error=maybe-uninitialized'})
Source('instructions.cc', append={'CXXFLAGS': '-Wno-error=ignored-qualifiers -Wno-error=type-limits -Wno-error=unused-but-set-variable -Wno-error=cpp -Wno-error=unused-variable -Wno-error=format= -Wno-error=maybe-uninitialized'})
Source('memory.cc', append={'CXXFLAGS': '-Wno-error=ignored-qualifiers -Wno-error=format'})
Source('ptx-stats.cc', append={'CXXFLAGS': '-Wno-error=ignored-qualifiers'})
Source('ptx_ir.cc', append={'CXXFLAGS': '-Wno-error=ignored-qualifiers -Wno-error=format'})
Source('ptx_loader.cc', append={'CXXFLAGS': '-Wno-error=ignored-qualifiers -Wno-error=format -Wno-error=format-truncation='})
Source('ptx_parser.cc', append={'CXXFLAGS': '-Wno-error=ignored-qualifiers -Wno-error=format -Wno-error=type-limits -Wno-error=maybe-uninitialized'})
Source('ptx_sim.cc', append={'CXXFLAGS': '-Wno-error=ignored-qualifiers -Wno-error=implicit-fallthrough -Wno-error=unused-function -Wno-error=format -Wno-error=maybe-uninitialized'})
Source('lex.ptx_.cc', append={'CFLAGS': '-Wno-error=ignored-qualifiers -Wno-error=unused-function'})
Source('lex.ptxinfo_.cc', append={'CFLAGS': '-Wno-error=ignored-qualifiers -Wno-error=unused-function'})
Source('ptxinfo.tab.cc', append={'CFLAGS': '-Wno-error=ignored-qualifiers'})
Source('ptx.tab.cc', append={'CFLAGS': '-Wno-error=ignored-qualifiers'})
Source('decuda_pred_table/decuda_pred_table.cc', append={'CXXFLAGS': '-Wno-error=ignored-qualifiers'})
